// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	protocol "virtualdesktop/internal/protocol"
)

// MockPeer is an autogenerated mock type for the Peer type
type MockPeer struct {
	mock.Mock
}

type MockPeer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeer) EXPECT() *MockPeer_Expecter {
	return &MockPeer_Expecter{mock: &_m.Mock}
}

// Receive provides a mock function with given fields: _a0
func (_m *MockPeer) Receive(_a0 context.Context) (protocol.Message, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 protocol.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (protocol.Message, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) protocol.Message); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(protocol.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPeer_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type MockPeer_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockPeer_Expecter) Receive(_a0 interface{}) *MockPeer_Receive_Call {
	return &MockPeer_Receive_Call{Call: _e.mock.On("Receive", _a0)}
}

func (_c *MockPeer_Receive_Call) Run(run func(_a0 context.Context)) *MockPeer_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPeer_Receive_Call) Return(_a0 protocol.Message, _a1 error) *MockPeer_Receive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPeer_Receive_Call) RunAndReturn(run func(context.Context) (protocol.Message, error)) *MockPeer_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0, _a1
func (_m *MockPeer) Send(_a0 context.Context, _a1 protocol.Message) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.Message) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPeer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockPeer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 protocol.Message
func (_e *MockPeer_Expecter) Send(_a0 interface{}, _a1 interface{}) *MockPeer_Send_Call {
	return &MockPeer_Send_Call{Call: _e.mock.On("Send", _a0, _a1)}
}

func (_c *MockPeer_Send_Call) Run(run func(_a0 context.Context, _a1 protocol.Message)) *MockPeer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.Message))
	})
	return _c
}

func (_c *MockPeer_Send_Call) Return(_a0 error) *MockPeer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPeer_Send_Call) RunAndReturn(run func(context.Context, protocol.Message) error) *MockPeer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPeer creates a new instance of MockPeer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeer {
	mock := &MockPeer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
