// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	damage "virtualdesktop/internal/damage"

	mock "github.com/stretchr/testify/mock"
)

// MockCapture is an autogenerated mock type for the Capture type
type MockCapture struct {
	mock.Mock
}

type MockCapture_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCapture) EXPECT() *MockCapture_Expecter {
	return &MockCapture_Expecter{mock: &_m.Mock}
}

// Capture provides a mock function with given fields: _a0, _a1
func (_m *MockCapture) Capture(_a0 context.Context, _a1 uint32) (damage.Image, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Capture")
	}

	var r0 damage.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) (damage.Image, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) damage.Image); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(damage.Image)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCapture_Capture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capture'
type MockCapture_Capture_Call struct {
	*mock.Call
}

// Capture is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uint32
func (_e *MockCapture_Expecter) Capture(_a0 interface{}, _a1 interface{}) *MockCapture_Capture_Call {
	return &MockCapture_Capture_Call{Call: _e.mock.On("Capture", _a0, _a1)}
}

func (_c *MockCapture_Capture_Call) Run(run func(_a0 context.Context, _a1 uint32)) *MockCapture_Capture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *MockCapture_Capture_Call) Return(_a0 damage.Image, _a1 error) *MockCapture_Capture_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCapture_Capture_Call) RunAndReturn(run func(context.Context, uint32) (damage.Image, error)) *MockCapture_Capture_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCapture creates a new instance of MockCapture. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCapture(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCapture {
	mock := &MockCapture{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
