// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	protocol "virtualdesktop/internal/protocol"
)

// MockInput is an autogenerated mock type for the Input type
type MockInput struct {
	mock.Mock
}

type MockInput_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInput) EXPECT() *MockInput_Expecter {
	return &MockInput_Expecter{mock: &_m.Mock}
}

// Button provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockInput) Button(_a0 context.Context, _a1 protocol.Button, _a2 protocol.Action) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Button")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protocol.Button, protocol.Action) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInput_Button_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Button'
type MockInput_Button_Call struct {
	*mock.Call
}

// Button is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 protocol.Button
//   - _a2 protocol.Action
func (_e *MockInput_Expecter) Button(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockInput_Button_Call {
	return &MockInput_Button_Call{Call: _e.mock.On("Button", _a0, _a1, _a2)}
}

func (_c *MockInput_Button_Call) Run(run func(_a0 context.Context, _a1 protocol.Button, _a2 protocol.Action)) *MockInput_Button_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protocol.Button), args[2].(protocol.Action))
	})
	return _c
}

func (_c *MockInput_Button_Call) Return(_a0 error) *MockInput_Button_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInput_Button_Call) RunAndReturn(run func(context.Context, protocol.Button, protocol.Action) error) *MockInput_Button_Call {
	_c.Call.Return(run)
	return _c
}

// Key provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockInput) Key(_a0 context.Context, _a1 uint16, _a2 protocol.Action, _a3 uint8) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Key")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint16, protocol.Action, uint8) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInput_Key_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Key'
type MockInput_Key_Call struct {
	*mock.Call
}

// Key is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uint16
//   - _a2 protocol.Action
//   - _a3 uint8
func (_e *MockInput_Expecter) Key(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockInput_Key_Call {
	return &MockInput_Key_Call{Call: _e.mock.On("Key", _a0, _a1, _a2, _a3)}
}

func (_c *MockInput_Key_Call) Run(run func(_a0 context.Context, _a1 uint16, _a2 protocol.Action, _a3 uint8)) *MockInput_Key_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint16), args[2].(protocol.Action), args[3].(uint8))
	})
	return _c
}

func (_c *MockInput_Key_Call) Return(_a0 error) *MockInput_Key_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInput_Key_Call) RunAndReturn(run func(context.Context, uint16, protocol.Action, uint8) error) *MockInput_Key_Call {
	_c.Call.Return(run)
	return _c
}

// Move provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockInput) Move(_a0 context.Context, _a1 uint32, _a2 uint32) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Move")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInput_Move_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Move'
type MockInput_Move_Call struct {
	*mock.Call
}

// Move is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uint32
//   - _a2 uint32
func (_e *MockInput_Expecter) Move(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockInput_Move_Call {
	return &MockInput_Move_Call{Call: _e.mock.On("Move", _a0, _a1, _a2)}
}

func (_c *MockInput_Move_Call) Run(run func(_a0 context.Context, _a1 uint32, _a2 uint32)) *MockInput_Move_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32))
	})
	return _c
}

func (_c *MockInput_Move_Call) Return(_a0 error) *MockInput_Move_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInput_Move_Call) RunAndReturn(run func(context.Context, uint32, uint32) error) *MockInput_Move_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseAll provides a mock function with given fields: _a0
func (_m *MockInput) ReleaseAll(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInput_ReleaseAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseAll'
type MockInput_ReleaseAll_Call struct {
	*mock.Call
}

// ReleaseAll is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockInput_Expecter) ReleaseAll(_a0 interface{}) *MockInput_ReleaseAll_Call {
	return &MockInput_ReleaseAll_Call{Call: _e.mock.On("ReleaseAll", _a0)}
}

func (_c *MockInput_ReleaseAll_Call) Run(run func(_a0 context.Context)) *MockInput_ReleaseAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInput_ReleaseAll_Call) Return(_a0 error) *MockInput_ReleaseAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInput_ReleaseAll_Call) RunAndReturn(run func(context.Context) error) *MockInput_ReleaseAll_Call {
	_c.Call.Return(run)
	return _c
}

// Wheel provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockInput) Wheel(_a0 context.Context, _a1 int16, _a2 int16) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Wheel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int16, int16) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInput_Wheel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wheel'
type MockInput_Wheel_Call struct {
	*mock.Call
}

// Wheel is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int16
//   - _a2 int16
func (_e *MockInput_Expecter) Wheel(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockInput_Wheel_Call {
	return &MockInput_Wheel_Call{Call: _e.mock.On("Wheel", _a0, _a1, _a2)}
}

func (_c *MockInput_Wheel_Call) Run(run func(_a0 context.Context, _a1 int16, _a2 int16)) *MockInput_Wheel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int16), args[2].(int16))
	})
	return _c
}

func (_c *MockInput_Wheel_Call) Return(_a0 error) *MockInput_Wheel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInput_Wheel_Call) RunAndReturn(run func(context.Context, int16, int16) error) *MockInput_Wheel_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInput creates a new instance of MockInput. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInput(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInput {
	mock := &MockInput{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
