// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	client "virtualdesktop/internal/client"

	mock "github.com/stretchr/testify/mock"
)

// MockRenderer is an autogenerated mock type for the Renderer type
type MockRenderer struct {
	mock.Mock
}

type MockRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRenderer) EXPECT() *MockRenderer_Expecter {
	return &MockRenderer_Expecter{mock: &_m.Mock}
}

// Present provides a mock function with given fields: _a0
func (_m *MockRenderer) Present(_a0 client.Snapshot) {
	_m.Called(_a0)
}

// MockRenderer_Present_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Present'
type MockRenderer_Present_Call struct {
	*mock.Call
}

// Present is a helper method to define mock.On call
//   - _a0 client.Snapshot
func (_e *MockRenderer_Expecter) Present(_a0 interface{}) *MockRenderer_Present_Call {
	return &MockRenderer_Present_Call{Call: _e.mock.On("Present", _a0)}
}

func (_c *MockRenderer_Present_Call) Run(run func(_a0 client.Snapshot)) *MockRenderer_Present_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(client.Snapshot))
	})
	return _c
}

func (_c *MockRenderer_Present_Call) Return() *MockRenderer_Present_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRenderer_Present_Call) RunAndReturn(run func(client.Snapshot)) *MockRenderer_Present_Call {
	_c.Run(run)
	return _c
}

// NewMockRenderer creates a new instance of MockRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRenderer {
	mock := &MockRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
