// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	protocol "virtualdesktop/internal/protocol"

	mock "github.com/stretchr/testify/mock"
)

// MockInputSender is an autogenerated mock type for the InputSender type
type MockInputSender struct {
	mock.Mock
}

type MockInputSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInputSender) EXPECT() *MockInputSender_Expecter {
	return &MockInputSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: _a0
func (_m *MockInputSender) Send(_a0 protocol.Message) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(protocol.Message) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInputSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockInputSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 protocol.Message
func (_e *MockInputSender_Expecter) Send(_a0 interface{}) *MockInputSender_Send_Call {
	return &MockInputSender_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *MockInputSender_Send_Call) Run(run func(_a0 protocol.Message)) *MockInputSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(protocol.Message))
	})
	return _c
}

func (_c *MockInputSender_Send_Call) Return(_a0 error) *MockInputSender_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInputSender_Send_Call) RunAndReturn(run func(protocol.Message) error) *MockInputSender_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInputSender creates a new instance of MockInputSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInputSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInputSender {
	mock := &MockInputSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
