// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	client "virtualdesktop/internal/client"

	mock "github.com/stretchr/testify/mock"
)

// MockStateObserver is an autogenerated mock type for the StateObserver type
type MockStateObserver struct {
	mock.Mock
}

type MockStateObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateObserver) EXPECT() *MockStateObserver_Expecter {
	return &MockStateObserver_Expecter{mock: &_m.Mock}
}

// ConnectionState provides a mock function with given fields: _a0, _a1
func (_m *MockStateObserver) ConnectionState(_a0 client.ConnectionState, _a1 error) {
	_m.Called(_a0, _a1)
}

// MockStateObserver_ConnectionState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectionState'
type MockStateObserver_ConnectionState_Call struct {
	*mock.Call
}

// ConnectionState is a helper method to define mock.On call
//   - _a0 client.ConnectionState
//   - _a1 error
func (_e *MockStateObserver_Expecter) ConnectionState(_a0 interface{}, _a1 interface{}) *MockStateObserver_ConnectionState_Call {
	return &MockStateObserver_ConnectionState_Call{Call: _e.mock.On("ConnectionState", _a0, _a1)}
}

func (_c *MockStateObserver_ConnectionState_Call) Run(run func(_a0 client.ConnectionState, _a1 error)) *MockStateObserver_ConnectionState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(client.ConnectionState), args[1].(error))
	})
	return _c
}

func (_c *MockStateObserver_ConnectionState_Call) Return() *MockStateObserver_ConnectionState_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStateObserver_ConnectionState_Call) RunAndReturn(run func(client.ConnectionState, error)) *MockStateObserver_ConnectionState_Call {
	_c.Run(run)
	return _c
}

// NewMockStateObserver creates a new instance of MockStateObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateObserver {
	mock := &MockStateObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
